### ISSUE TITLE
NcML update task list

### ISSUE THREAD

**Issue by brianmckenna** [ioos/comt_catalog#24]
# outstanding
- [ ] SELFE needs standard_name for latitude and longitude
- [ ] FVCOM (extratropical) `siglay` is a 2D variable, but `siglay` is also used as an index, is this legal? [example](http://comt.sura.org/thredds/dodsC/comt_1_archive_full/inundation_extratropical/UMASS_FVCOM/2005_3D_final_run_waves_only/00_dir.ncml.ascii?u[0:1:1][0:1:1][0:1:1])
- [ ] several datasets use `cell_methods: time: point` point doesn't seem to be a valid dimension, is this necessary?
# complete
- [x] example completed sub-issue
